---
# ansible-galaxy collection install -r requirements.yml
collections:
  - community.general

# ansible-galaxy role install -r requirements.yml
roles:
  - name: user_management
    src: xenion1987.user_management
  - name: sudoers
    src: xenion1987.sudoers
