---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_connection: ssh
    ansible_ssh_common_args: |
      -o IdentitiesOnly=yes
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
    ansible_ssh_transfer_method: scp
  children:
    # local:
    #   hosts:
    #     localhost:
    #       ansible_connection: local
    clients:
      children:
        deb_based:
          children:
            debian:
              hosts:
                ansible-client-debian12:
                  ansible_ssh_user: root
                  ansible_ssh_private_key_file: ~/.ssh/id_rsa
            ubuntu:
              hosts:
                ansible-client-ubuntu24:
                  ansible_ssh_user: root
                  ansible_ssh_private_key_file: ~/.ssh/id_rsa
                # ansible-client-ubuntu22:
                #   ansible_ssh_user: root
                #   ansible_ssh_private_key_file: ~/.ssh/id_rsa
                # ansible-client-ubuntu20:
                #   ansible_ssh_user: root
                #   ansible_ssh_private_key_file: ~/.ssh/id_rsa
        rpm_based:
          children:
            almalinux:
              hosts:
                ansible-client-alma9:
                  ansible_ssh_user: root
                  ansible_ssh_private_key_file: ~/.ssh/id_rsa
                # ansible-client-alma8:
                #   ansible_ssh_user: root
                #   ansible_ssh_private_key_file: ~/.ssh/id_rsa
            # suse:
            #   hosts:
            #     ansible-client-suse:
            #       ansible_ssh_user: root
            #       ansible_ssh_private_key_file: ~/.ssh/id_rsa
