FROM ubuntu:22.04
RUN apt update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt install -y --no-install-recommends \
    dialog \
    apt-utils \
    sudo \
    curl \
    iproute2 \
    python3 \
    openssh-server
RUN mkdir -p /run/sshd
CMD ["/usr/sbin/sshd", "-D"]
