FROM almalinux:9
ARG TZ
RUN dnf update -y && \
    dnf install --allowerasing -y \
    dnf-utils \
    sudo \
    curl \
    iproute \
    python3 \
    tzdata \
    openssh-clients \
    openssh-server \
    && dnf clean all
ENV TZ=${TZ:-Europe/Berlin}
RUN mkdir -p /run/sshd && ssh-keygen -A \
    && install --directory --mode=0700 /root/.ssh \
    && echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
COPY ./ssh-keys/clients/authorized_keys /root/.ssh/authorized_keys
RUN chown $(id -u):$(id -g) /root/.ssh/authorized_keys && chmod 644 /root/.ssh/authorized_keys
CMD ["/usr/sbin/sshd", "-D"]
