FROM almalinux:8
RUN dnf update -y && \
    dnf install -y \
    dnf-utils \
    sudo \
    curl \
    iproute \
    python3 \
    tzdata \
    openssh-clients \
    openssh-server \
    && dnf clean all
ENV TZ='Europe/Berlin'
RUN mkdir -p /run/sshd && ssh-keygen -A
CMD ["/usr/sbin/sshd", "-D"]
