FROM ubuntu:22.04
RUN sed -i 's,http://archive,http://de.archive,' /etc/apt/sources.list
RUN apt update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt install -y --no-install-recommends \
    dialog \
    apt-utils \
    sudo \
    curl \
    iproute2 \
    tzdata \
    python3 \
    openssh-server \
    && rm -rf /var/lib/apt/lists/*
ENV TZ='Europe/Berlin'
RUN mkdir -p /run/sshd && ssh-keygen -A
CMD ["/usr/sbin/sshd", "-D"]
