FROM opensuse/leap:15
RUN zypper update -y && \
    zypper install -y \
    sudo \
    curl \
    iproute2 \
    python3 \
    openssh-clients \
    openssh-server \
    && zypper clean -a
RUN mkdir -p /run/sshd && ssh-keygen -A
CMD ["/usr/sbin/sshd", "-D"]
