FROM debian:11
RUN apt update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt install -y --no-install-recommends \
    dialog \
    apt-utils \
    sudo \
    curl \
    tzdata \
    iproute2 \
    python3 \
    openssh-server \
    && rm -rf /var/lib/apt/lists/*
ENV TZ='Europe/Berlin'
RUN mkdir -p /run/sshd && ssh-keygen -A
CMD ["/usr/sbin/sshd", "-D"]
