---
- name: Play for managing linux users
  hosts: all
  gather_facts: false

  # Requires role 'user_management' mentioned in 'requirements.yml'
  roles:
    - role: user_management
      vars:
        user_management_default_secondary_groups: [playground]
        user_management_users:
          - name: john.doe
            state: present
            ssh_public_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDW6k6qtP1YfJ7eOSN1zDf8C6lTJuV+ethOvEJwTKJrGoQrKKukVfedjUL+e7XMszVT57iiV8rC+syZsJ6wkwJR2ahOUlU9hACbRc+X5mmVROLKlO+NaxrbMzsTJXeCJK6Oo+05f2kSPqGfjV3CZSq4Xv5mUMhaDkGUg/rqG5BIdqFDwirqxbUbPOIYeosLT1tbgxHvOTwsUqulEZS5h8mOt1Hahi1ZrfUOyharJvpc5rzYk/hq1zwTXTNtArOLCaSbvY+o61BAsnQBzg6Z+Elyrox53kWW8c0MuG0iPfehqW20eE9xZVBQfwutLmMHMNeUD2UwLDfxnoVXIlgn5T4Z4F2uMyKWKl9IsoIuguizX98SuASEXg4wsAEf2MSCxwk7AGO3yCgqRsnm7sIEEdvxUIewcuZn1ZtN0c3UjcsqRnoXgBOXpynsRStdZTPTM+o1LGma+Wp8FkMH1ZnuQ+BrCQ1ENKcS4oeTcG91Ud9Yiu/qfWVU64RrYpz0JvHWoApdzM73Xro2Sz9BuQH5uSCIya8PNEqGdH1GRDxbDkv41+scWwq/5i5CSlWmNogU377tPld9hqJJA//eniErgKO/QSJKmaDDzFe+eQh6F2Kn/NUVKqbPHbDlkYAZGT37L5iCOG1By55wwnemz40GS2Wo+a4nViDJGhuFty+4yR8fWQ== ansible-playground_20231122_194549
    - role: sudoers
      vars:
        sudoers_install_sudo: true

        sudoers_manage_group_files: true
        sudoers_groups:
          - name: sudoers_group_file
            group: sudoers_mygroupname
            commands:
              - ALL
            nopassword: true
            state: present

        sudoers_manage_user_files: true
        sudoers_users:
          - name: sudoers_user_file
            user: john.doe
            commands:
              - ALL
            nopassword: true
            state: present
